version: '3.8'

services:
  api:
    build: .
    image: adarshlohi/cicd-pipeline:latest
    container_name: cicd-pipeline-container
    ports:
      - '8080:4000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/']
      interval: 30s
      timeout: 10s
      retries: 3
