name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull the docker image from Dockerhub
        run: |
          echo "Pulling latest image..."
          sudo docker pull adarshlohi/cicd-pipeline:latest

      - name: Delete the old docker container
        run: |
          echo "Removing old container if exists..."
          sudo docker rm -f cicd-pipeline-container || true

      - name: Run the docker container
        run: |
          echo "Starting new container..."
          sudo docker run -d -p 8080:4000 --name cicd-pipeline-container adarshlohi/cicd-pipeline:latest

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          sudo docker ps | grep cicd-pipeline-container

      - name: Start the service using Docker Compose
        run: |
          echo "Starting the service using Docker Compose..."
          sudo docker-compose up -d

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          sudo docker-compose ps
