name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: adarshlohi
        password: dckr_pat_QstbUjNnmCZXyGk2Tf0ifmFy71I        # Changed from DOCKER_TOKEN
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: adarshlohi/cicd-pipeline:latest
